language: cpp
before_install:
  - mkdir -p ~/bin
  - curl -L -o ~/bin/yaggo https://github.com/gmarcais/yaggo/releases/download/v1.5.9/yaggo
  - chmod a+rx ~/bin/yaggo
script: autoreconf -i && ./configure YAGGO=~/bin/yaggo && make && make check
addons:
  artifacts:
    paths:
      - $(git ls-files -o | grep '\.log$' | tr "\n" ":")
  s3_region: "us-east-1"
